### ISSUE TITLE
IIS Collector generating panic on Win32_PerfRawData_W3SVC_WebServiceCache

### ISSUE THREAD

**Issue by szook** [martinlindhe/wmi_exporter#225]
One of our servers must be in a wonky state since `Win32_PerfRawData_W3SVC_WebServiceCache` returns an empty list: 
```
PS C:\> Get-WmiObject -Query "select * from Win32_PerfRawData_W3SVC_WebServiceCache"
PS C:\>
```
This state is causing the wmi_exporter to panic when the IIS collector is enabled: 
```
C:\>"C:\Program Files\wmi_exporter\wmi_exporter.exe" --log.format logger:eventlog?name=wmi_exporter --collectors.enabled cpu,cs,logical_disk,net,os,process,service,system,tcp,iis,vmware --telemetry.addr :9100
WARN[0000] No where-clause specified for service collector. This will generate a very large number of metrics!  msource="service.go:44"
WARN[0000] No where-clause specified for process collector. This will generate a very large number of metrics!  msource="process.go:55"
INFO[0000] Enabled collectors: os, service, vmware, process, system, cs, net, tcp, cpu, iis, logical_disk  msource="exporter.go:230"
INFO[0000] Starting WMI exporter (version=0.3.3, branch=master, revision=f3072bb4f3016b87c350b13e77eb96fd4cfe49a8)  msource="exporter.go:241"
INFO[0000] Build context (go=go1.10, user=appvyr-win\appveyor@APPVYR-WIN, date=20180519-07:19:39)  msource="exporter.go:242"
INFO[0000] Starting server on :9100                      msource="exporter.go:245"
panic: runtime error: index out of range

goroutine 49 [running]:
github.com/martinlindhe/wmi_exporter/collector.(*IISCollector).collect(0xc0421c4000, 0xc042058ae0, 0x0, 0x0, 0x0)
        c:/gopath/src/github.com/martinlindhe/wmi_exporter/collector/iis.go:1741 +0x89e8
github.com/martinlindhe/wmi_exporter/collector.(*IISCollector).Collect(0xc0421c4000, 0xc042058ae0, 0xba6620, 0x0)
        c:/gopath/src/github.com/martinlindhe/wmi_exporter/collector/iis.go:817 +0x43
main.execute(0xc04201a1b6, 0x3, 0x95f660, 0xc0421c4000, 0xc042058ae0)
        c:/gopath/src/github.com/martinlindhe/wmi_exporter/exporter.go:100 +0x85
main.WmiCollector.Collect.func1(0xc042058ae0, 0xc04201cdf0, 0xc04201a1b6, 0x3, 0x95f660, 0xc0421c4000)
        c:/gopath/src/github.com/martinlindhe/wmi_exporter/exporter.go:74 +0x5a
created by main.WmiCollector.Collect
        c:/gopath/src/github.com/martinlindhe/wmi_exporter/exporter.go:73 +0x110
```

We are running wmi_exporter version 0.3.3

Even though there is something wrong with our server, I think the wmi_exporter code should fail gracefully rather than panic. 

The panic is being triggered because the code is not checking to make sure the `dst_cache` slice has elements before trying to access the first element.  

see line https://github.com/martinlindhe/wmi_exporter/blob/v0.3.3/collector/iis.go#L1741

Solution would be a matter of wrapping a `if len(dst_cache) > 0 {}` block around the `prometheus.MustNewConstMetric` commands.

**Comment by carlpett** [comment]
Ouch. Not sure how that could happen, but nicely fixed. Will make a release with this in a few minutes.
