### ISSUE TITLE
panic when `Win32_PerfRawData_PerfOS_System` returns empty result set

### ISSUE THREAD

**Issue by szook** [martinlindhe/wmi_exporter#240]
on one of our servers we found that the `wmi_exporter` service was perpetually restarting.

Upon inspection, found that it was throwing a panic during a scrape: 
```
panic: runtime error: index out of range

goroutine 29 [running]:
github.com/martinlindhe/wmi_exporter/collector.(*SystemCollector).collect(0xc04212f410, 0xc04204a0c0, 0x0, 0x0, 0x0)
        c:/gopath/src/github.com/martinlindhe/wmi_exporter/collector/system.go:101 +0x4c7
github.com/martinlindhe/wmi_exporter/collector.(*SystemCollector).Collect(0xc04212f410, 0xc04204a0c0, 0xbe0620, 0x0)
        c:/gopath/src/github.com/martinlindhe/wmi_exporter/collector/system.go:73 +0x43
main.execute(0xc0420840ab, 0x6, 0x995b40, 0xc04212f410, 0xc04204a0c0)
        c:/gopath/src/github.com/martinlindhe/wmi_exporter/exporter.go:100 +0x85
main.WmiCollector.Collect.func1(0xc04204a0c0, 0xc04201c070, 0xc0420840ab, 0x6, 0x995b40, 0xc04212f410)
        c:/gopath/src/github.com/martinlindhe/wmi_exporter/exporter.go:74 +0x5a
created by main.WmiCollector.Collect
        c:/gopath/src/github.com/martinlindhe/wmi_exporter/exporter.go:73 +0x110
```

That code location is trying to iterate over the results of querying the `Win32_PerfRawData_PerfOS_System` class.  When I query that class in powershell, I'm not getting a result set: 
```
PS C:\Windows\system32> Get-WmiObject -Query "select * from Win32_PerfRawData_PerfOS_System"
PS C:\Windows\system32>
```

So the root cause is that the wmi subsystem on the server is having issues and likely needs a reboot/rebuild, but at the same time, the `wmi_exporter` should be able to gracefully deal with this situation.

**Comment by szook** [comment]
I'm thinking we can fix this in one of two ways: 

1) Add a `if len(dst_cache) > 0 {}` block around the `ch <- prometheus.MustNewConstMetric()` commands like on https://github.com/martinlindhe/wmi_exporter/pull/226

2) Return an error if the result set is empty:
```
if len(dst_cache) == 0 {
  return nil, errors.New("WMI Class returned empty result set")
}
```
Thoughts?
